name: usuful_functions
description: A collections of usuful functions to make .
version: 0.1.0+1
homepage: https://github.com/AlexanderMendivil/UF
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
